name: cubit_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  sizer: ^3.0.4
  supabase_flutter: ^2.8.0
  http: ^1.2.2
  excel: ^4.0.6
  file_picker: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/locales/
    - assets/images/
  fonts:
    - family: myFont
      fonts:
        - asset: assets/fonts/SixtyfourConvergence-Regular.ttf